from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.PADDING = True
_C.DRUG.KERNEL_SIZE=3
_C.DRUG.DROPOUT = 0.2
_C.DRUG.D2_DNN_INPUT_DIM=16*64
_C.DRUG.D2_DNN_HIDDEN_DIM=1024
_C.DRUG.D2_DNN_OUT_DIM=128
_C.DRUG.D3_INPUT_DIM=64
_C.DRUG.D3_DNN_INPUT_DIM=64
_C.DRUG.D3_DNN_HIDDEN_DIM=1024
_C.DRUG.D3_DNN_OUT_DIM=128
_C.DRUG.D_DNN_INPUT_DIM=2048
_C.DRUG.D_DNN_OUT_DIM=256

# Protein light attention feature extractor
_C.PROTEIN_LA = CN()
_C.PROTEIN_LA.INPUT_DIM = 1024
_C.PROTEIN_LA.EMBEDDING_DIM = 128
_C.PROTEIN_LA.KERNEL_SIZE=9
_C.PROTEIN_LA.PADDING = True

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "MLP"
_C.DECODER.IN_DIM = 512
_C.DECODER.HIDDEN_DIM = [1024,1024,512]
_C.DECODER.OUT_DIM = 2

# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 500
_C.SOLVER.SEED = 1
_C.SOLVER.BATCH_SIZE = 32
_C.SOLVER.LR = 5.0e-4
_C.SOLVER.WEIGHT_DECAY = 1.0e-5
_C.SOLVER.LOSS_FUNCTION = 'dirichlet_loss'# ev_v1



# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = "./runs"

_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()
